# Question 1

In [2]:
import numpy as np

In [4]:
new_array = np.arange(2,51,3)
new_array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2

In [5]:
import numpy as np

In [6]:
lst1 = []   
lst2 = []   
lst1 = [int(item) for item in input("Enter the list 1 elements:").split()] 
lst2 = [int(item) for item in input("Enter the list 2 elements:").split()] 
arr1 = np.array(lst1)
arr2 = np.array(lst2)
arr = np.concatenate((arr1,arr2))
print("After converting and concatenating the numpy array:",arr)
sorted_arr = np.sort(arr)
print("The Final sorted array:",sorted_arr)

Enter the list 1 elements:13 81 21 32 45 31 17
Enter the list 2 elements:90 56 34 72 54 34
After converting and concatenating the numpy array: [13 81 21 32 45 31 17 90 56 34 72 54 34]
The Final sorted array: [13 17 21 31 32 34 34 45 54 56 72 81 90]


# Question 3

In [7]:
import numpy as np

In [8]:
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5],[3, 8, 9]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  9


# Question 4

In [9]:
import numpy as np

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (5, 2))
print('1D Numpy array:')
print(arr)
print('2D Numpy array:')
print(arr_2d)


1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Question 5

In [12]:
import numpy as np

In [13]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6], [7, 8]]) 
print("Vertical stacking:\n", np.vstack((a, b)))
print("\nHorizontal stacking:\n", np.hstack((a, b))) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


# Question 6

In [14]:
import numpy as np

In [17]:
a = np.array( [10,10,20,10,20,20,20,30, 30,40,40,50,55] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("unique values and counts are ")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 40 40 50 55]
unique values and counts are 
[[10 20 30 40 50 55]
 [ 3  4  2  2  1  1]]
